#!/bin/bash

set -e
ln -fs ~/etc/images ~/current/public/system
ln -fs ~/etc/newrelic.yml ~/current/config/newrelic.yml
ln -fs ~/etc/database.yml ~/current/config/database.yml
ln -fs ~/etc/secret_token.rb ~/current/confir/initializers/secret_token.rb

cd ~/current/
RAILS_ENV=production bundle exec rake assets:precompile
RAILS_ENV=production bundle exec rake db:migrate

/etc/init.d/app restart
