#!/bin/sh

set -e
ln -s /home/sqale/etc/database.yml /home/sqale/current/config/database.yml
ln -s /home/sqale/etc/secret_token.rb /home/sqale/current/confir/initializers/secret_token.rb

cd /home/sqale/current/
bundle install --path=vendor/bundle --quiet --without development:test
bundle exec rake assets:precompile
bundle exec rake db:migrate

/etc/init.d/app restart
